---
#
# 2018 Becki True
#
# Section 1 configuration Level 1 per the Benchmark Document 
# The Level 2 tasks are in a separate playbook because they
# can break things on a running server
#

  - name: create (touch) /etc/modprobe.d/CIS.conf
    file:
       path: /etc/modprobe.d/CIS.conf
       state: touch
       owner: root
       group: root
       mode: 0644
    tags:
        - scored
        - section1.1
        - section1.1.1
        - section1.1.1.1
        - level1
        - cis_control13 
  - name: 1.1.1.1 Ensure mounting of cramfs filesystems is diabled (Scored)
    lineinfile:
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install cramfs /bin/true'
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.1
       - level1
       - cis_control13
  - name: 1.1.1.1 unload the cramfs module 
    shell: rmmod cramfs
    register: cramfs_result
    failed_when: >
       cramfs_result.rc != 0 and ("not currently loaded" not in cramfs_result.stderr)
    changed_when: "cramfs_result.rc == 0"
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.1
       - level1
       - cis_control13
  - name: 1.1.1.2 Ensure mounting of freevxfs filesystems is disabled (Scored) 
    lineinfile:
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install freevxfs /bin/true'
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.2
       - level1
       - cis_control13
  - name: 1.1.1.2 unload the freevxfs module
    shell: rmmod freevxfs 
    register: freevxfs_result
    failed_when: >
      freevxfs_result.rc != 0 and ("not currently loaded" not in freevxfs_result.stderr)
    changed_when: "freevxfs_result.rc == 0"
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.2
       - level1
       - cis_control13
  - name: 1.1.1.3 Ensure mounting of jffs2 filesystems is disabled (Scored)
    lineinfile:
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install jffs2 /bin/true'
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.3
       - level1
       - cis_control13
  - name: 1.1.1.3 unload the jffs2 filesystem module
    shell: rmmod jffs2
    register: jffs2_result
    failed_when: >
      jffs2_result.rc != 0 and ("not currently loaded" not in jffs2_result.stderr)
    changed_when: "jffs2_result.rc == 0"
    tags:
       - scored      
       - section1.1
       - section1.1.1
       - section1.1.1.3
       - level1
       - cis_control13
  - name: 1.1.1.4 Ensure mounting of hfs filesystems is disabled (Scored)
    lineinfile:
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install hfs /bin/true'
    tags:
       - scored      
       - section1.1
       - section1.1.1
       - section1.1.1.4
       - level1
       - cis_control13
  - name: 1.1.1.4 unload hfs filesystem module
    shell: rmmod hfs
    register: hfs_result
    failed_when: >
      hfs_result.rc != 0 and ("not currently loaded" not in hfs_result.stderr)
    changed_when: "hfs_result.rc == 0"
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.4
       - level1
       - cis_control13
  - name: 1.1.1.5 Ensure mounting of hfsplus filesystems is disabled (Scored)
    lineinfile:
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install hfsplus /bin/true'
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.5
       - level1
       - cis_control13
  - name: 1.1.1.5 unload hfsplus filesystem module
    shell: rmmod hfsplus
    register: hfsplus_result
    failed_when: >
      hfsplus_result.rc != 0 and ("not currently loaded" not in hfsplus_result.stderr)
    changed_when: "hfsplus_result.rc == 0"
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.5
       - level1
       - cis_control13
  - name: 1.1.1.6 Ensure mounting of squashfs filesystems is disabled (Scored)
    lineinfile:   
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install squashfs /bin/true'
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.6
       - level1
       - cis_control13
  - name: 1.1.1.6 unload squashfs filesystem module
    shell: rmmod squashfs
    register: squashfs_result
    failed_when: >
      squashfs_result.rc != 0 and ("not currently loaded" not in squashfs_result.stderr)
    changed_when: "squashfs_result.rc == 0"
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.6
       - level1
       - cis_control13
  - name: 1.1.1.7 Ensure mounting of udf filesystems is disabled (Scored)
    lineinfile:
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install udf /bin/true'
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.7
       - level1
       - cis_control13
  - name: 1.1.1.7 unload udf filesystem module
    shell: rmmod udf
    register: udf_result
    failed_when: >
      udf_result.rc != 0 and ("not currently loaded" not in udf_result.stderr)
    changed_when: "udf_result.rc == 0"
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.7
       - level1
       - cis_control13
  - name: 1.1.1.8 Ensure mounting of FAT filesystems is disabled (Scored)
    lineinfile:     
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install vfat /bin/true'
    tags:    
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.8
       - level1
       - cis_control13
  - name: 1.1.1.8 unload FAT filesystem module
    shell: rmmod vfat
    register: vfat_result
    failed_when: >
      vfat_result.rc != 0 and ("not currently loaded" not in vfat_result.stderr)
    changed_when: "vfat_result.rc == 0"
    tags: 
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.8
       - level1
       - cis_control13
  - name: 1.1.3 - 1.1.5 Ensure nodev, nosuid, noexec options set on /tmp partition if it exists (Scored)
    shell: cat /etc/fstab | grep /tmp 
    register: tmp_partition_result
    ignore_errors: yes
    tags:
      - scored
      - section1.1
      - section1.1.3
      - level1
  - name: 1.1.3 - 1.1.5  manually update /etc/fstab
    debug: msg="manually updating /etc/fstab to ensure nodev, nosuid, noexec options are configured"
    when: "tmp_partition_result.rc == 0"
    tags:
      - scored
      - section1.1
      - section1.1.3
      - level1
  - name: 1.1.3 - 1.1.5 update /etc/fstab with nodev, nosuid, noexec options for /tmp partition
    mount:
      src: /tmp
      path: /
      state: present
      fstype: tmpfs
      opts: "rw,nosuid,nodev,noexec,relatime"
    when: "tmp_partition_result.rc == 0"
    tags:
      - scored
      - section1.1
      - section1.1.3
      - section1.1.4
      - section1.1.5
      - level1

