---
#
# 2018 Becki True
#
# Section 1 of the CIS Amazon Linux Benchmark is File System Configuration
#

- import_tasks: section_01_level1.yml
  tags:
     - section1
     - level1

- import_tasks: section_01_level2.yml
  tags:
     - section1
     - level2
