---
#
# 2018 Becki True
#
# Level 1 per the Benchmark Document 
#

  - name: create /etc/modprobe.d/CIS.conf
    file:
       path: /etc/modprobe.d/CIS.conf
       state: touch
       owner: root
       group: root
       mode: 0644
    tags:
        - scored
        - section1.1
        - section1.1.1
        - section1.1.1.1
        - cis_control13 
  - name: 1.1.1.1 Ensure mounting of cramfs filesystems is diabled (Scored)
    lineinfile:
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install cramfs /bin/true'
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.1
       - cis_control13
  - name: 1.1.1.1 unload the cramfs module 
    command: rmmod cramfs
    ignore_errors: yes
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.1
       - cis_control13
  - name: 1.1.1.2 Ensure mounting of freevxfs filesystems is disabled (Scored) 
    lineinfile:
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install freevxfs /bin/true'
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.2
       - cis_control13
  - name: 1.1.1.2 unload the freevxfs module
    command: rmmod freevxfs 
    ignore_errors: yes
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.2
       - cis_control13
  - name: 1.1.1.3 Ensure mounting of jffs2 filesystems is disabled (Scored)
    lineinfile:
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install jffs2 /bin/true'
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.3
       - cis_control13
  - name: 1.1.1.3 unload the jffs2 filesystem module
    command: rmmod jffs2
    ignore_errors: yes
    tags:
       - scored      
       - section1.1
       - section1.1.1
       - section1.1.1.3
       - cis_control13
  - name: 1.1.1.4 Ensure mounting of hfs filesystems is disabled (Scored)
    lineinfile:
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install hfs /bin/true'
    tags:
       - scored      
       - section1.1
       - section1.1.1
       - section1.1.1.4
       - cis_control13
  - name: 1.1.1.4 unload hfs filesystem module
    command: rmmod hfs
    ignore_errors: yes
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.4
       - cis_control13
  - name: 1.1.1.5 Ensure mounting of hfsplus filesystems is disabled (Scored)
    lineinfile:
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install hfsplus /bin/true'
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.5
       - cis_control13
  - name: 1.1.1.5 unload hfsplus filesystem module
    command: rmmod hfsplus
    ignore_errors: yes
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.5
       - cis_control13
  - name: 1.1.1.6 Ensure mounting of squashfs filesystems is disabled (Scored)
    lineinfile:   
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install squashfs /bin/true'
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.6
       - cis_control13
  - name: 1.1.1.6 unload squashfs filesystem module
    command: rmmod squashfs
    ignore_errors: yes
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.6
       - cis_control13
  - name: 1.1.1.7 Ensure mounting of udf filesystems is disabled (Scored)
    lineinfile:
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install udf /bin/true'
    tags:
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.7
       - cis_control13
  - name: 1.1.1.7 unload udf filesystem module
    command: rmmod udf
    ignore_errors: yes
    tags:
      - scored
       - section1.1
       - section1.1.1
       - section1.1.1.7
       - cis_control13
  - name: 1.1.1.8 Ensure mounting of FAT filesystems is disabled (Scored)
    lineinfile:     
      state: present
      path: /etc/modprobe.d/CIS.conf
      line: 'install vfat /bin/true'
    tags:    
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.8
       - cis_control13
  - name: 1.1.1.8 unload FAT filesystem module
    command: rmmod vfat
    ignore_errors: yes
    tags: 
       - scored
       - section1.1
       - section1.1.1
       - section1.1.1.8
       - cis_control1
